username: DIMMANEE

name: physics blog

description: physics blog

avatar: https://avatars.githubusercontent.com/u/203735438?v=4


collections:
  archives:
    output: true
    permalink: /archives/:title

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: http://github.com/DIMMANEE
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow: 
  youtube: 
  googleplus: 

disqus:

google_analytics:

url: http://dimmanee.github.io

baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _posts/2000-1-01-example-post.md
  - _archives/2000-1-01-example-archive.md
